# Generated by Django 3.1.3 on 2020-11-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docscrapapp', '0002_auto_20201120_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapper',
            name='resume_file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
