# Generated by Django 3.1.3 on 2020-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docscrapapp', '0003_auto_20201120_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapper',
            name='resume_file',
            field=models.FileField(upload_to=''),
        ),
    ]
